# Пример для проекта на Node.js
jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v2
      # Устанавливаем Node.js
      - uses: actions/setup-node@v1
      # Ставим зависимости
      - run: make install
      # Запускаем линтер
      - run: make test
      # Запускаем тесты
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
